# Generated by Django 4.2.5 on 2023-10-07 01:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0002_dancer_program_alter_dancer_date_of_birth'),
        ('slack', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slack_id', models.CharField(max_length=100)),
                ('dancer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='team.dancer')),
            ],
        ),
        migrations.CreateModel(
            name='Workspace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=100)),
                ('season', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='team.season')),
            ],
        ),
        migrations.DeleteModel(
            name='Token',
        ),
        migrations.AddField(
            model_name='user',
            name='workspace',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='slack.workspace'),
        ),
    ]
