# Generated by Django 4.2.5 on 2023-10-02 15:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dancer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('date_of_birth', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Season',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Style',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Subteam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('dancers', models.ManyToManyField(to='team.dancer')),
                ('season', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='team.season')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='team.team')),
            ],
        ),
        migrations.AddField(
            model_name='season',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='team.team'),
        ),
        migrations.CreateModel(
            name='Routine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('choreographers', models.ManyToManyField(related_name='choreographer_set', to='team.dancer')),
                ('dancers', models.ManyToManyField(related_name='dancer_set', to='team.dancer')),
                ('style', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='team.style')),
                ('subteam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='team.subteam')),
            ],
        ),
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accepted', models.BooleanField(null=True)),
                ('dancer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='team.dancer')),
                ('routine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='team.routine')),
            ],
        ),
        migrations.AddField(
            model_name='dancer',
            name='captain_seasons',
            field=models.ManyToManyField(related_name='captain_set', to='team.season'),
        ),
        migrations.AddField(
            model_name='dancer',
            name='choreographer_seasons',
            field=models.ManyToManyField(related_name='choreographer_set', to='team.season'),
        ),
        migrations.AddField(
            model_name='dancer',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='team.team'),
        ),
    ]
