# Generated by Django 4.2.5 on 2023-10-07 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0002_dancer_program_alter_dancer_date_of_birth'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dancer',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='dancer',
            name='program',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
